theme: jekyll-theme-slate
github:
  project_title: "Contact Pic Linkimator"
  project_tagline: "Sync your Contact Pics to the latest profile images!"
  repository_url: https://bnutz.github.io/contactpiclinkimator
